# Generated by Django 2.0.7 on 2019-08-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_number',
            field=models.IntegerField(default=1),
        ),
    ]
