# Generated by Django 2.1 on 2019-08-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('homework', '0002_homework_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='section',
        ),
        migrations.AddField(
            model_name='homework',
            name='Course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
    ]
