# Generated by Django 2.1 on 2019-08-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190201_1605'),
        ('homework', '0004_homeworktraker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('title', 'Course')},
        ),
    ]
