# Generated by Django 2.1 on 2019-08-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_auto_20190810_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='video_clip_link_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='video_clip_link_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='video_clip_name_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='video_clip_name_2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
