# Generated by Django 2.1 on 2019-08-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_auto_20190811_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='quetions',
            field=models.TextField(null=True),
        ),
    ]
