# Generated by Django 2.1 on 2019-08-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_homework_quetions'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='quetions_image',
            field=models.ImageField(null=True, upload_to='homework/'),
        ),
        migrations.AddField(
            model_name='homeworktraker',
            name='start_time_video_1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='homeworktraker',
            name='start_time_video_2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='homeworktraker',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='homeworktraker',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
