# Generated by Django 2.1 on 2019-08-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_auto_20190820_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='due_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
