# Generated by Django 2.1 on 2019-08-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180926_2209'),
        ('homework', '0009_homework_due_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeworktraker',
            unique_together={('Student', 'Homework')},
        ),
    ]
