# Generated by Django 2.1 on 2019-08-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0010_auto_20190820_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='quetions',
        ),
        migrations.AddField(
            model_name='homework',
            name='video_clip_link_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='video_clip_name_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homeworktraker',
            name='start_time_video_3',
            field=models.DateTimeField(null=True),
        ),
    ]
